version: "3"
services:

    # scheduler & monitoring service
    airflow-webserver:
        hostname: myairflow
        container_name: airflow_container
        image: 'puckel/docker-airflow:latest'
        ports:
            - '8085:8080'
        networks:
            - dataworld
        volumes:
            - airflow-data:/usr/local/airflow/data
            - ./airflow/logs:/usr/local/airflow/logs
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/requirements/requirements.txt:/requirements.txt
            - ./airflow/airflow.cfg:/usr/local/airflow/airflow.cfg
        environment:
            - GUNICORN_CMD_ARGS=--log-level warning
        restart: on-failure
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myairflow:8080/admin/"]
            interval: 30s
            timeout: 20s
            retries: 3

    # relational database
    postgres:
        hostname: mypostgres
        container_name: postgres_container
        image: 'postgres:14-bullseye'  # latest image as of 2021-11-08
        environment:
            POSTGRES_USER: 'postgres'
            POSTGRES_PASSWORD: 'postgres'
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - dataworld
        restart: on-failure
        
    # database administration tool
    pgadmin:
        hostname: mypgadmin
        container_name: pgadmin_container
        image: 'dpage/pgadmin4:6.1'  # latest image as of 2021-11-08
        environment:
            PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
            PGADMIN_DEFAULT_PASSWORD: 'admin'
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
            - ./pgadmin:/home
        ports:
            - "5050:80"
        networks:
            - dataworld
        restart: on-failure
        
    # object storage
    minio:
        hostname: myminio
        container_name: minio_container
        image: 'bitnami/minio:latest'
        environment:
            MINIO_ROOT_USER: minio_admin
            MINIO_ROOT_PASSWORD: minio_password
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - './minio/data:/data'
        networks:
            - dataworld
        healthcheck:
            test: ["CMD", "curl", "-f", "http://myminio:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - portainer-data:/data
        ports:
            - 9009:9000

volumes:
    airflow-data:
    postgres:
    pgadmin:
    portainer-data:

networks:
    dataworld:
        driver: bridge
